# Generated by Django 2.1 on 2018-08-17 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolname', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TempReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date Recorded')),
                ('temp', models.PositiveSmallIntegerField(verbose_name='Temperature')),
                ('humidity', models.PositiveSmallIntegerField(verbose_name='Humidity')),
                ('school', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
