# Generated by Django 2.0.7 on 2018-08-01 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolchoice', models.CharField(choices=[('SAB', 'Sabin')], default='SAB', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='TempReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date Recorded')),
                ('temp', models.PositiveSmallIntegerField(verbose_name='Temperature')),
                ('humidity', models.PositiveSmallIntegerField(verbose_name='Humidty')),
            ],
        ),
    ]
