# Generated by Django 2.0.7 on 2018-08-01 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperatures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempreading',
            name='humidity',
            field=models.PositiveSmallIntegerField(verbose_name='Humidity'),
        ),
    ]
