# Generated by Django 2.1 on 2018-08-28 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperatures', '0002_remove_school_schoolname'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='schoolname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
