# Generated by Django 2.1 on 2018-08-03 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperatures', '0002_auto_20180801_0206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='schoolchoice',
        ),
        migrations.AddField(
            model_name='school',
            name='schoolname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
